package polling

func Pusher(){
	// HERE YOU ADD YOUR CODE TO CONNECT / SEND DATA TO YOUR SERVICE.
	// EDIT AS YOU SEE FIT (aka parameters etc)
	// PLEASE DONT COMMIT THIS CODE. KEEP IT FOR YOURSELF LOCAL SINCE MULTIPLE PEOPLE WILL BE EDITING THIS.
}